CREATE TABLE T_TDSPW_PACIENTE (
    CD_PACIENTE NUMBER(6,0) PRIMARY KEY,
    NM_PACIENTE VARCHAR2(80) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    NR_CPF VARCHAR2(11) NOT NULL,
    DS_EMAIL VARCHAR2(80) NOT NULL,
    NR_TELEFONE VARCHAR2(11)
)
CREATE SEQUENCE SQ_TDSPW_PACIENTE NOCYCLE NOCACHE;

CREATE TABLE T_TDSPW_MEDICO(
   CD_MEDICO NUMBER(6,0) PRIMARY KEY,
   NM_MEDICO VARCHAR2(80) NOT NULL,
   DT_NASCIMENTO DATE NOT NULL,
   NR_CRM VARCHAR2(8) NOT NULL,
   DS_ESPECIALIDADE VARCHAR2(60) NOT NULL,
   VL_SALARIO NUMBER(7,2) NOT NULL
)
CREATE SEQUENCE SQ_TDSPW_MEDICO NOCYCLE NOCACHE;