CREATE TABLE T_TDSPW_PACIENTE (
    CD_PACIENTE NUMBER(6,0) PRIMARY KEY,
    NM_PACIENTE VARCHAR2(80) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    NR_CPF VARCHAR2(11) NOT NULL,
    DS_EMAIL VARCHAR2(80) NOT NULL,
    NR_TELEFONE VARCHAR2(11)
)
CREATE SEQUENCE SQ_TDSPW_PACIENTE NOCYCLE NOCACHE;

CREATE TABLE T_TDSPW_MEDICO(
   CD_MEDICO NUMBER(6,0) PRIMARY KEY,
   NM_MEDICO VARCHAR2(80) NOT NULL,
   DT_NASCIMENTO DATE NOT NULL,
   NR_CRM VARCHAR2(8) NOT NULL,
   DS_ESPECIALIDADE VARCHAR2(60) NOT NULL,
   VL_SALARIO NUMBER(7,2) NOT NULL
)
CREATE SEQUENCE SQ_TDSPW_MEDICO NOCYCLE NOCACHE;

CREATE TABLE T_TDSPW_CONSULTA
    (
     CD_CONSULTA    NUMBER (11)  PRIMARY KEY ,
     DT_INICIO      DATE  NOT NULL ,
     DT_FIM         DATE  NOT NULL ,
     DS_LINK        VARCHAR2 (30 CHAR)  NOT NULL ,
     DS_OBSERVACOES VARCHAR2 (80 CHAR)  NOT NULL ,
     DS_STATUS      VARCHAR2 (40 CHAR)  NOT NULL ,
     CD_PACIENTE    NUMBER (5) NOT NULL ,
     CD_MEDICO      NUMBER (5) NOT NULL,
     CONSTRAINT FK_CD_PACIENTE FOREIGN KEY (CD_PACIENTE) REFERENCES T_TDSPW_PACIENTE,
     CONSTRAINT FK_CD_MEDICO FOREIGN KEY (CD_MEDICO) REFERENCES T_TDSPW_MEDICO
    );
    CREATE SEQUENCE SQ_TDSPW_CONSULTA NOCYCLE NOCACHE

    CREATE TABLE T_TDSPW_PARENTE
        (
         CD_PARENTE    NUMBER (5)  PRIMARY KEY ,
         NM_PARENTE    VARCHAR2 (60 CHAR)  NOT NULL ,
         DS_PARENTESCO VARCHAR2 (30 CHAR)  NOT NULL ,
         NR_TELEFONE NUMBER (11)  NOT NULL ,
         CD_PACIENTE   NUMBER (5)  NOT NULL,
         CONSTRAINT FK_CD_PARENTE_PACIENTE FOREIGN KEY (CD_PACIENTE) REFERENCES T_TDSPW_PACIENTE
        ) ;
    CREATE SEQUENCE SQ_TDSPW_PARENTE NOCYCLE NOCACHE


CREATE TABLE T_TDSPW_LEMBRETE
   (
     CD_LEMBRETE NUMBER (5) PRIMARY KEY ,
     DS_MENSAGEM VARCHAR2 (60 CHAR)  NOT NULL ,
     DT_ENVIO    DATE  NOT NULL ,
     CD_PARENTE  NUMBER (5)
     CONSTRAINT SEQUENCE FK_CD_LEMBRETE_PARENTE FOREIGN KEY (CD_PARENTE) REFERENCES T_TDSPW_PARENTE
   );
    CREATE SEQUENCE SQ_TDSPW_LEMBRETE NOCYCLE NOCACHE